import type { InteldocState } from './types'
import {
  ACCESS_BY_DEPARTMENT_SEED,
  ACCESS_INCIDENTS_SEED,
  ADOPTION_BY_DEPARTMENT_SEED,
  ADOPTION_BY_DOCTOR_SEED,
  AUDIT_EVENTS_SEED,
  COMPLIANCE_CHECKS_SEED,
  COMPLIANCE_STATE_SEED,
  FUNNEL_SEED,
  KPI_TREND_SEED,
  PILOT_GOAL_SEED,
  PILOT_KPIS_SEED,
} from '../data/adminMockData'

/**
 * Seed state for the demo.
 * - p1 is reserved for the patient created by the entry flow (Anna Petrova).
 * - p2 / p3 populate the doctor's patient list so it doesn't render empty.
 */
export const SEED: InteldocState = {
  currentPatientId: null,
  doctorActivePatientId: null,
  currentDoctorId: 'd1',

  webAuth: null,

  hasCompletedOnboarding: false,
  accountDraft: null,
  accessSigned: false,

  esignRecords: [],
  consentBundles: [],

  clinics: [
    {
      id: 'enc',
      name: 'Эндокринологический научный центр',
      shortName: 'ЭНЦ',
      department: 'Отделение диабетологии',
    },
  ],

  doctors: [
    {
      id: 'd1',
      name: 'Соколов А.В.',
      specialty: 'Эндокринолог',
      clinicId: 'enc',
    },
  ],

  patients: [
    {
      id: 'p2',
      name: 'Волков Сергей Николаевич',
      dob: '1968-03-12',
      gender: 'male',
      phone: '+7 (916) 555-12-02',
      identifiers: { oms: '7700000000000002' },
      partnerClinic: 'enc',
      department: 'Отделение диабетологии',
      attendingDoctorId: 'd1',
      createdAt: '2026-04-05T10:00:00Z',
      prepCompletedAt: '2026-04-25T19:42:00Z',
      prepTimeSpentMin: 14,
      diagnosis: { label: 'Диабет 2 типа', confirmed: true },
    },
    {
      id: 'p3',
      name: 'Михайлова Елена Викторовна',
      dob: '1975-11-02',
      gender: 'female',
      phone: '+7 (916) 555-12-03',
      identifiers: { oms: '7700000000000003' },
      partnerClinic: 'enc',
      department: 'Отделение диабетологии',
      attendingDoctorId: 'd1',
      createdAt: '2026-04-08T09:30:00Z',
      prepCompletedAt: '2026-04-22T16:15:00Z',
      prepTimeSpentMin: 9,
      diagnosis: { label: 'Диабет 2 типа', confirmed: false },
    },
    {
      // p4 — secondary demo patient with a critical-lab signature so the
      // critical-lab banner fires here without polluting the main flow on p2.
      id: 'p4',
      name: 'Волков Андрей Михайлович',
      dob: '1962-07-19',
      gender: 'male',
      phone: '+7 (916) 555-12-04',
      identifiers: { oms: '7700000000000004' },
      partnerClinic: 'enc',
      department: 'Отделение диабетологии',
      attendingDoctorId: 'd1',
      createdAt: '2026-04-12T11:00:00Z',
      prepCompletedAt: '2026-04-26T20:05:00Z',
      prepTimeSpentMin: 11,
      diagnosis: { label: 'Диабет 2 типа, декомпенсация', confirmed: true },
    },
  ],

  accessGrants: [
    {
      id: 'ag-p2',
      patientId: 'p2',
      clinicId: 'enc',
      scope: 'lifetime-clinic',
      grantedAt: '2026-04-05T10:01:00Z',
      department: 'Эндокринология',
      lastViewedAt: '2026-04-24T09:12:00Z',
    },
    {
      id: 'ag-p3',
      patientId: 'p3',
      clinicId: 'enc',
      scope: 'lifetime-clinic',
      grantedAt: '2026-04-08T09:31:00Z',
      department: 'Эндокринология',
      lastViewedAt: '2026-04-22T15:48:00Z',
    },
    {
      id: 'ag-p4',
      patientId: 'p4',
      clinicId: 'enc',
      scope: 'lifetime-clinic',
      grantedAt: '2026-04-12T11:01:00Z',
      department: 'Эндокринология',
      lastViewedAt: '2026-04-26T20:10:00Z',
    },
  ],

  analyses: [
    {
      // Prior HbA1c uploaded by the patient as historical context — feeds the
      // «Динамика с прошлого визита» block on the doctor Обзор.
      id: 'an-p2-hba1c-prev',
      patientId: 'p2',
      type: 'HbA1c',
      label: 'Гликированный гемоглобин (HbA1c)',
      date: '2026-01-18',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: { HbA1c: '8.6 %', дата: '18.01.2026', норма: '< 6.5 %' },
      ocrFieldMeta: {
        HbA1c: {
          ref: '< 6.5 %',
          refMax: 6.5,
          numericValue: 8.6,
          unit: '%',
        },
      },
      status: 'acknowledged',
      uploadedAt: '2026-04-05T10:28:00Z',
    },
    {
      // Prior Холестерин/ЛПНП uploaded as patient history — supports delta.
      id: 'an-p2-chol-prev',
      patientId: 'p2',
      type: 'cholesterol',
      label: 'Холестерин общий + ЛПНП',
      date: '2026-01-18',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: {
        Холестерин: '5.7 ммоль/л',
        ЛПНП: '3.4 ммоль/л',
        дата: '18.01.2026',
      },
      ocrFieldMeta: {
        Холестерин: {
          ref: '< 5.2 ммоль/л',
          refMax: 5.2,
          numericValue: 5.7,
          unit: 'ммоль/л',
        },
        ЛПНП: {
          ref: '< 3.0 ммоль/л',
          refMax: 3.0,
          numericValue: 3.4,
          unit: 'ммоль/л',
        },
      },
      status: 'acknowledged',
      uploadedAt: '2026-04-05T10:29:00Z',
    },
    {
      id: 'an-p2-hba1c',
      patientId: 'p2',
      type: 'HbA1c',
      label: 'Гликированный гемоглобин (HbA1c)',
      date: '2026-03-22',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: { HbA1c: '7.8 %', дата: '22.03.2026', норма: '< 6.5 %' },
      ocrFieldMeta: {
        HbA1c: {
          ref: '< 6.5 %',
          refMax: 6.5,
          numericValue: 7.8,
          unit: '%',
        },
      },
      status: 'acknowledged',
      uploadedAt: '2026-04-05T10:30:00Z',
    },
    {
      id: 'an-p2-glu',
      patientId: 'p2',
      type: 'glucose',
      label: 'Глюкоза крови натощак',
      date: '2026-03-22',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: {
        Глюкоза: '7.1 ммоль/л',
        дата: '22.03.2026',
        норма: '3.9–5.6 ммоль/л',
      },
      ocrFieldMeta: {
        Глюкоза: {
          ref: '3.9–5.6 ммоль/л',
          refMin: 3.9,
          refMax: 5.6,
          numericValue: 7.1,
          unit: 'ммоль/л',
          lowConfidence: true,
        },
      },
      status: 'uploaded',
      uploadedAt: '2026-04-05T10:31:00Z',
    },
    {
      id: 'an-p2-creat',
      patientId: 'p2',
      type: 'creatinine',
      label: 'Креатинин сыворотки',
      date: '2026-03-22',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: {
        Креатинин: '88 мкмоль/л',
        дата: '22.03.2026',
        норма: '62–115 мкмоль/л',
      },
      ocrFieldMeta: {
        Креатинин: {
          ref: '62–115 мкмоль/л',
          refMin: 62,
          refMax: 115,
          numericValue: 88,
          unit: 'мкмоль/л',
        },
      },
      status: 'acknowledged',
      uploadedAt: '2026-04-05T10:32:00Z',
    },
    {
      id: 'an-p2-chol',
      patientId: 'p2',
      type: 'cholesterol',
      label: 'Холестерин общий + ЛПНП',
      date: '2026-03-22',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: {
        Холестерин: '6.1 ммоль/л',
        ЛПНП: '3.8 ммоль/л',
        дата: '22.03.2026',
      },
      ocrFieldMeta: {
        Холестерин: {
          ref: '< 5.2 ммоль/л',
          refMax: 5.2,
          numericValue: 6.1,
          unit: 'ммоль/л',
        },
        ЛПНП: {
          ref: '< 3.0 ммоль/л',
          refMax: 3.0,
          numericValue: 3.8,
          unit: 'ммоль/л',
        },
      },
      status: 'uploaded',
      uploadedAt: '2026-04-05T10:33:00Z',
    },
    {
      // p4 prior HbA1c — patient-uploaded history.
      id: 'an-p4-hba1c-prev',
      patientId: 'p4',
      type: 'HbA1c',
      label: 'Гликированный гемоглобин (HbA1c)',
      date: '2026-01-30',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: { HbA1c: '9.6 %', дата: '30.01.2026', норма: '< 6.5 %' },
      ocrFieldMeta: {
        HbA1c: {
          ref: '< 6.5 %',
          refMax: 6.5,
          numericValue: 9.6,
          unit: '%',
        },
      },
      status: 'acknowledged',
      uploadedAt: '2026-04-12T11:10:00Z',
    },
    {
      // p4 current HbA1c — critical, drives the critical-lab banner.
      id: 'an-p4-hba1c',
      patientId: 'p4',
      type: 'HbA1c',
      label: 'Гликированный гемоглобин (HbA1c)',
      date: '2026-04-18',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: { HbA1c: '11.4 %', дата: '18.04.2026', норма: '< 6.5 %' },
      ocrFieldMeta: {
        HbA1c: {
          ref: '< 6.5 %',
          refMax: 6.5,
          numericValue: 11.4,
          unit: '%',
        },
      },
      status: 'uploaded',
      uploadedAt: '2026-04-26T19:40:00Z',
    },
    {
      // p4 fasting glucose — also at the critical threshold.
      id: 'an-p4-glu',
      patientId: 'p4',
      type: 'glucose',
      label: 'Глюкоза крови натощак',
      date: '2026-04-18',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: {
        Глюкоза: '14.2 ммоль/л',
        дата: '18.04.2026',
        норма: '3.9–5.6 ммоль/л',
      },
      ocrFieldMeta: {
        Глюкоза: {
          ref: '3.9–5.6 ммоль/л',
          refMin: 3.9,
          refMax: 5.6,
          numericValue: 14.2,
          unit: 'ммоль/л',
        },
      },
      status: 'uploaded',
      uploadedAt: '2026-04-26T19:42:00Z',
    },
    {
      id: 'an-p3-chol',
      patientId: 'p3',
      type: 'cholesterol',
      label: 'Холестерин общий + ЛПНП',
      date: '2026-03-30',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: {
        Холестерин: '5.4 ммоль/л',
        ЛПНП: '3.6 ммоль/л',
        дата: '30.03.2026',
      },
      ocrFieldMeta: {
        Холестерин: {
          ref: '< 5.2 ммоль/л',
          refMax: 5.2,
          numericValue: 5.4,
          unit: 'ммоль/л',
        },
        ЛПНП: {
          ref: '< 3.0 ммоль/л',
          refMax: 3.0,
          numericValue: 3.6,
          unit: 'ммоль/л',
        },
      },
      status: 'uploaded',
      uploadedAt: '2026-04-08T11:00:00Z',
    },
  ],

  documents: [
    {
      id: 'doc-p2-passport',
      patientId: 'p2',
      type: 'passport',
      label: 'Паспорт',
      originalFileUrl: '',
      qualityCheck: 'clear',
      status: 'uploaded',
      uploadedAt: '2026-04-05T10:25:00Z',
      structureStatus: 'structured',
    },
    {
      id: 'doc-p2-oms',
      patientId: 'p2',
      type: 'oms',
      label: 'Полис ОМС',
      originalFileUrl: '',
      qualityCheck: 'clear',
      status: 'uploaded',
      uploadedAt: '2026-04-05T10:27:00Z',
      structureStatus: 'structured',
    },
    {
      id: 'doc-p2-referral',
      patientId: 'p2',
      type: 'referral',
      label: 'Направление от районной поликлиники',
      originalFileUrl: '',
      qualityCheck: 'acceptable',
      status: 'uploaded',
      uploadedAt: '2026-04-06T08:11:00Z',
      structureStatus: 'original-only',
    },
    {
      id: 'doc-p4-passport',
      patientId: 'p4',
      type: 'passport',
      label: 'Паспорт',
      originalFileUrl: '',
      qualityCheck: 'clear',
      status: 'uploaded',
      uploadedAt: '2026-04-12T11:05:00Z',
      structureStatus: 'structured',
    },
    {
      id: 'doc-p4-oms',
      patientId: 'p4',
      type: 'oms',
      label: 'Полис ОМС',
      originalFileUrl: '',
      qualityCheck: 'clear',
      status: 'uploaded',
      uploadedAt: '2026-04-12T11:07:00Z',
      structureStatus: 'structured',
    },
    {
      id: 'doc-p3-passport',
      patientId: 'p3',
      type: 'passport',
      label: 'Паспорт',
      originalFileUrl: '',
      qualityCheck: 'clear',
      status: 'uploaded',
      uploadedAt: '2026-04-08T09:35:00Z',
      structureStatus: 'structured',
    },
    {
      id: 'doc-p3-oms',
      patientId: 'p3',
      type: 'oms',
      label: 'Полис ОМС',
      originalFileUrl: '',
      qualityCheck: 'clear',
      status: 'uploaded',
      uploadedAt: '2026-04-08T09:38:00Z',
      structureStatus: 'structured',
    },
  ],
  complaints: [
    {
      id: 'cm-p2-1',
      patientId: 'p2',
      text: 'Утром цифры на глюкометре стабильно выше 8 — переживаю, что компенсация ушла.',
      createdAt: '2026-04-24T18:30:00Z',
      tags: ['glucose'],
      priority: 1,
    },
    {
      id: 'cm-p2-2',
      patientId: 'p2',
      text: 'К вечеру быстро устаю и отекают ноги — не понимаю, связано ли это с дозой.',
      createdAt: '2026-04-24T18:32:00Z',
      tags: ['energy'],
      priority: 2,
    },
    {
      id: 'cm-p2-3',
      patientId: 'p2',
      text: 'Хочу понять, нужно ли мне дополнительно сдавать что-то по почкам.',
      createdAt: '2026-04-25T19:15:00Z',
      tags: ['other'],
      priority: 3,
    },
    {
      id: 'cm-p2-4',
      patientId: 'p2',
      text: 'Иногда тяжело засыпать — думаю, это от тревоги перед визитом.',
      createdAt: '2026-04-25T19:18:00Z',
      tags: ['sleep'],
    },
    {
      id: 'cm-p4-1',
      patientId: 'p4',
      text: 'Сахар скачет, по утрам бывает за 13 ммоль/л — тяжело держать под контролем.',
      createdAt: '2026-04-26T19:55:00Z',
      tags: ['glucose'],
      priority: 1,
    },
    {
      id: 'cm-p4-2',
      patientId: 'p4',
      text: 'Пью воду чаще обычного и сильнее устаю к вечеру.',
      createdAt: '2026-04-26T19:57:00Z',
      tags: ['energy'],
      priority: 2,
    },
    {
      id: 'cm-p3-1',
      patientId: 'p3',
      text: 'Хочу обсудить, можно ли пересмотреть схему — устаю и набираю вес.',
      createdAt: '2026-04-21T20:10:00Z',
      tags: ['weight', 'energy'],
      priority: 1,
    },
    {
      id: 'cm-p3-2',
      patientId: 'p3',
      text: 'Беспокоят перепады настроения, особенно по вечерам.',
      createdAt: '2026-04-21T20:14:00Z',
      tags: ['mood'],
      priority: 2,
    },
  ],
  planItems: [
    {
      id: 'pi-p2-1',
      patientId: 'p2',
      requestId: 'req-p2-1',
      analysisType: 'HbA1c',
      label: 'HbA1c — повторный контроль',
      reason: 'Сравнить с показателем месячной давности.',
      status: 'uploaded',
      linkedAnalysisId: 'an-p2-hba1c',
      createdAt: '2026-04-15T08:00:00Z',
      dueDate: '2026-04-28',
    },
    {
      id: 'pi-p2-2',
      patientId: 'p2',
      requestId: 'req-p2-1',
      analysisType: 'creatinine',
      label: 'Креатинин + СКФ',
      reason: 'Базовая оценка функции почек.',
      status: 'acknowledged',
      linkedAnalysisId: 'an-p2-creat',
      createdAt: '2026-04-15T08:00:00Z',
      dueDate: '2026-04-28',
    },
    {
      id: 'pi-p2-3',
      patientId: 'p2',
      requestId: 'req-p2-1',
      analysisType: 'other',
      label: 'Микроальбумин в моче',
      reason: 'Скрининг диабетической нефропатии.',
      status: 'assigned',
      createdAt: '2026-04-15T08:00:00Z',
      dueDate: '2026-04-28',
    },
  ],
  doctorRequests: [
    {
      id: 'req-p2-1',
      patientId: 'p2',
      fromDoctorId: 'd1',
      title: 'Подготовка к плановому приёму',
      body: 'Сдайте, пожалуйста, перечисленные анализы за неделю до визита.',
      planItemIds: ['pi-p2-1', 'pi-p2-2', 'pi-p2-3'],
      createdAt: '2026-04-15T08:00:00Z',
      seenByPatient: true,
    },
  ],
  appointments: [
    {
      id: 'apt-p2-main',
      patientId: 'p2',
      doctorId: 'd1',
      type: 'main',
      date: '2026-05-04T10:00:00Z',
      status: 'scheduled',
      createdAt: '2026-04-05T10:02:00Z',
    },
    {
      id: 'apt-p4-main',
      patientId: 'p4',
      doctorId: 'd1',
      type: 'main',
      date: '2026-05-04T11:00:00Z',
      status: 'scheduled',
      createdAt: '2026-04-12T11:02:00Z',
    },
    {
      id: 'apt-p3-main',
      patientId: 'p3',
      doctorId: 'd1',
      type: 'main',
      date: '2026-05-06T11:30:00Z',
      status: 'scheduled',
      createdAt: '2026-04-08T09:32:00Z',
    },
  ],

  // ─── Admin slices (aggregate, no PII) ──────────────────────────────────────
  pilotKpis: PILOT_KPIS_SEED,
  pilotGoal: PILOT_GOAL_SEED,
  funnel: FUNNEL_SEED,
  adoptionByDepartment: ADOPTION_BY_DEPARTMENT_SEED,
  adoptionByDoctor: ADOPTION_BY_DOCTOR_SEED,
  kpiTrend: KPI_TREND_SEED,
  accessByDepartment: ACCESS_BY_DEPARTMENT_SEED,
  accessIncidents: ACCESS_INCIDENTS_SEED,
  auditEvents: AUDIT_EVENTS_SEED,
  complianceState: COMPLIANCE_STATE_SEED,
  complianceChecks: COMPLIANCE_CHECKS_SEED,
}
